name: Docker and Helm Push with Auto Versioning

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_new_version.outputs.new_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          echo "latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "v0.0.2")" >> $GITHUB_OUTPUT

      - name: Calculate new version
        id: set_new_version
        run: |
          latest_tag="${{ steps.get_latest_tag.outputs.latest_tag }}"
          echo "Latest tag: $latest_tag"

          # Extract the major, minor, and patch numbers
          IFS='.' read -r major minor patch <<< "${latest_tag//[!0-9.]/}"

          # Increment the patch version
          new_version="v$major.$minor.$((patch + 1))"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: calculate-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::132900311735:role/oiai-dev-github-role
          aws-region: us-east-1
      - name: Build Image
        run: |
          docker build -f docker/app/Dockerfile  -t 132900311735.dkr.ecr.us-east-1.amazonaws.com/oiai-dev-us-east-1-api-repo:development .

      - name: Push Docker image to Docker Hub
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 132900311735.dkr.ecr.us-east-1.amazonaws.com
          docker tag 132900311735.dkr.ecr.us-east-1.amazonaws.com/oiai-dev-us-east-1-api-repo:development 132900311735.dkr.ecr.us-east-1.amazonaws.com/oiai-dev-us-east-1-api-repo:${{ needs.calculate-version.outputs.new_version }}
          docker push 132900311735.dkr.ecr.us-east-1.amazonaws.com/oiai-dev-us-east-1-api-repo:${{ needs.calculate-version.outputs.new_version }}
          docker push 132900311735.dkr.ecr.us-east-1.amazonaws.com/oiai-dev-us-east-1-api-repo:development


  helm-package-and-push:
    runs-on: ubuntu-latest
    needs:
      - docker-build-and-push
      - calculate-version

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::132900311735:role/oiai-dev-github-role
          aws-region: us-east-1

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install s3 plugin
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Download Chart dependencies
        run: |
          helm dependency update ./charts/api

      - name: Package Helm chart
        run: |
          echo ${{ needs.calculate-version.outputs.new_version }}
          helm package ./charts/api --version ${{ needs.calculate-version.outputs.new_version }}
      
      - name: Temporary ls
        run: ls
      
      - name: Push Helm chart to Docker Hub
        env:
          HELM_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          HELM_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          helm repo add s3-repo s3://dg-oiai-charts/charts
          helm s3 push --force oiai-api-base-chart-${{ needs.calculate-version.outputs.new_version }}.tgz s3-repo
