name: Backend CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Load environment variables
        run: cp .env.example .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Alembic migrations
        run: alembic upgrade head

      - name: Build Docker image
        run: docker build -t your-docker-repo/backend:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push your-docker-repo/backend:${{ github.sha }}
          if: github.ref == 'refs/heads/dev'
          run: docker push your-docker-repo/backend:dev
